name: CI

on: [push, pull_request]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    name: test (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        build-type: [Release]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        cache: true

    - name: Compile with meson
      run: |
        if [ "${{ matrix.os }}" = "macos-latest" ]; then
          export CC=clang
          export CXX=clang++
        fi
        pixi run meson setup build --buildtype release
        pixi run meson compile -C build

    - name: Test with meson
      run: |
        pixi run meson test -C build --verbose

    - name: Compile and test without netcdf
      run: |
        if [ "${{ matrix.os }}" = "macos-latest" ]; then
          export CC=clang
          export CXX=clang++
        fi
        pixi run meson setup build_nonetcdf --buildtype release -Dwith_netcdf=false
        pixi run meson compile -C build_nonetcdf
        pixi run meson test -C build_nonetcdf --verbose
