name: prek
on:
  pull_request:
  push:
    branches: [main]
jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.3
    - name: Setup Pixi
      uses: prefix-dev/setup-pixi@v0.9.6
      with:
        cache: true
    - name: Install prek
      uses: taiki-e/install-action@prek
    - name: Run prek
      run: |
        pixi run prek run --all-files --show-diff-on-failure
      env:
        PREK_COLOR: always
